### ISSUE TITLE
PostgreSQL driver different schema how do it?

### ISSUE THREAD

**Issue by thenotsoft** [spiral/database#21]
I have a database and there is a public scheme and a test scheme in it. How can I create a table in a test  scheme ?
when I try to create this test.test_table, it is created in public with the name "test.test_table"

**Comment by wolfy-j** [comment]
Have you tried to alter search_path?

https://www.postgresql.org/docs/9.4/ddl-schemas.html

**Comment by thenotsoft** [comment]
search_path I don’t think it will help, since there are 2 different schemes with the same tables, the old database structure, which I cannot change now (

**Comment by wolfy-j** [comment]
I have not tried to change the base schema for the driver connection. I assume it means that we have to update all introspection queries. I need to think how to implement it.

**Comment by thenotsoft** [comment]
possible something like the database

    $this->database('default')->schema('test')->table('test_table')

**Comment by wolfy-j** [comment]
I assume it's ok from a syntax perspective, but we will need to check the SQL queries used for introspection. It will take some time.

**Comment by wolfy-j** [comment]
We will consider looking into such functionality next year.

**Comment by thenotsoft** [comment]
these changes in `Spiral\Database\Driver\Postgres\PostgresHandler` solved my problem, but it seems to me that this is not enough

```
public function hasTable(string $name): bool
{
        $schema = 'public';
        if (strpos($name, '.') !== false) {
            [$schema, $name] = explode('.', $name);
        }
        return (bool)$this->driver->query(
            "SELECT COUNT(table_name) FROM information_schema.tables WHERE table_schema = ?
          AND table_type = 'BASE TABLE' AND table_name = ?",
            [$schema, $name]
        )->fetchColumn();
}
```

```
public function getTableNames(): array
{
        $query = "SELECT * FROM information_schema.tables WHERE table_catalog = ?
          AND table_type = 'BASE TABLE' AND table_schema NOT IN ('pg_catalog', 'information_schema')";

        $tables = [];
        foreach ($this->driver->query($query, [$this->driver->getSource()]) as $row) {
            $tables[] = $row['table_name'];
        }

        return $tables;
}
```
what do you think about it?

**Comment by wolfy-j** [comment]
You also have to modify `getSchema` most likely, I think the sync functionality should work without any changes after that.

**Comment by thenotsoft** [comment]
create pull request with this changes ?

**Comment by wolfy-j** [comment]
If you can - yes please.

**Comment by thenotsoft** [comment]
table prefix in the current implementation, is a problem for making this change, need to do a lot more changes

**Comment by thenotsoft** [comment]
I started to implement namespace, continue in this direction or do you have other visions for this implementation ?

https://github.com/thenotsoft/database/commit/3dca2477445e18e0f22cfdb9d7ca1369f939b459

P.S: does not work with prefixes yet

**Comment by wolfy-j** [comment]
No objects at the moment, but I would recommend you to start with tests for your use-case.

**Comment by xorock** [comment]
Laravel has also 'schema' => env('DB_SCHEMA', 'public'), inside config/database.php. Can I set default schema in Spiral?

**Comment by wolfy-j** [comment]
Not at the moment. This feature still in pipeline, any help is appreciated.

**Comment by roxblnfk** [comment]
Resolved in the cycle/database package
