### ISSUE TITLE
ConnectionException  when executing an invalid request

### ISSUE THREAD

**Issue by vGhost2000** [spiral/database#22]
Простите, с английским будет гугл-транслейт..

При выполнении не корректного запроса в бд, падает ConnectionException  в то время как соединение с бд в общем то не терялось. Воспроизвести можно так, создаём тестовую модель с не корректными данными для запроса:

When an incorrect query is executed in the database, ConnectionException drops while the connection to the database is generally not lost. You can play it like this, create a test model with incorrect data for the query:

```
<?php
declare(strict_types=1);

namespace App\models\Db;

use Cycle\Annotated\Annotation\Entity;
use Cycle\Annotated\Annotation\Column;


/**
 * @Entity
 */
class Test
{

    /**
     * @var int
     * @Column(type = "primary")
     */
    public $test_id;


    /**
     * @var string
     * @Column(type="string", nullable=false)
     */
    public $name;

    /**
     *
     * @var string
     * @Column(type="json", nullable=false)
     */
    public $description = [];
}
```

Далее код который выполнит некорректный запрос

Next, the code that will execute the incorrect query
```
        $t = new Transaction($orm);
        $e = new Test();
        $e->name = 'azazaza';
        $t->persist($e);
        $t->run();
```

Результат: выкидывается ConnectionException:

Result: throws ConnectionException:

_Spiral\Database\Exception\StatementException\ConnectionException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '))' at line 2 in /var/www/vendor/spiral/database/src/Driver/MySQL/MySQLDriver.php at line 101
• caused by PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '))' at line 2 in /var/www/vendor/spiral/database/src/Driver/Driver.php at line 526_

**MariaDB**
version: 10.4.4-MariaDB-1:10.4.4+maria~bionic - mariadb.org binary distribution
Protocol version: 10
Official docker image: mariadb:10.4.4

**Comment by wolfy-j** [comment]
Thank you for the issue. Check 2.6.7
