### ISSUE TITLE
readonlySchema annotation don't work

### ISSUE THREAD

**Issue by vGhost2000** [spiral/database#27]
Создаём сущность, в параметрах указываем readonlySchema
```
/**
 * @Entity (readonlySchema = true)
 */
class SomeEntity
{
  ...
}
```
Выполняем команду: `php app.php cycle:migrate`
**Ожидаемый результат:** миграция на сущность не создаётся
**Фактический результат:** миграция создалась

<br /><br /><br />

Create an entity, specify readonlySchema in the parameters
```
/**
 * @Entity (readonlySchema = true)
 */
class SomeEntity
{
  ...
}
```
Run the command: `php app.php cycle:migrate`
**Expected result:** migration to the entity will not be created.
**Actual result:** migration created

![image](https://user-images.githubusercontent.com/3455060/71973283-027c4280-3228-11ea-953b-a0053c44dab6.png)

**Comment by wolfy-j** [comment]
Please check `cycle/migrations v1.0.8`.
