### ISSUE TITLE
Feature request: disableMigrations option

### ISSUE THREAD

**Issue by vGhost2000** [spiral/database#28]
# Feature request: disableMigrations option
Добавить в конфигурацию соединения boolean опцию disableMigrations которая глобально для соединения отключает миграции, в том числе создание таблицы migrations. Это полезно в следующих случаях:

1) в SphinxSearch/ManticoreSearch в принципе нет миграций и запрос на создание таблицы migrations валится.
2) К примеру, есть база, которая мигрируется другим проектом, и отслеживать её в спирали не следует, спираль имеет с ней соединение в, скажем, read-only режиме.

# Feature request: disableMigrations option
Add the disableMigrations (boolean) option to the connection configuration, which globally for the connection disables migrations, including the creation of the migrations table. This is useful in the following cases:

1) in SphinxSearch / ManticoreSearch, in principle, there are no migrations and the query to create the migrations table falls.
2) For example, there is a database that is being migrated by another project, and you should not track it in a spiral; the spiral has a connection to it in, say, read-only mode.

![image](https://user-images.githubusercontent.com/3455060/71973661-ea58f300-3228-11ea-8b4d-32e88fe1e4f3.png)

**Comment by wolfy-j** [comment]
I guess we can create NullHandler which does not write any changes into the database...

**Comment by wolfy-j** [comment]
Something like that should work: https://github.com/spiral/database/blob/master/src/Driver/ReadonlyHandler.php

I need to allocate some time to write tests for it and then we can add config option `readonlySchema`.

**Comment by wolfy-j** [comment]
I can advise what needs to be done if anyone wants to help with it.

**Comment by roxblnfk** [comment]
Привет, @vGhost2000.
В [новом релизе](https://github.com/spiral/migrations/releases/tag/v2.3.0) мигратора есть несколько изменений, которые покрывают кейсы `disableMigrations`:

- Таблица `migrations` теперь не создаётся в базе данных, для которой нет миграций.
- Соединения, настроенные как `readonly` (доступно, начиная с [spiral/database 2.9.0](https://github.com/spiral/database/releases/tag/v2.9.0)), будут пропускаться.
