### ISSUE TITLE
Feature request: AbstractTable::getComparator type hint

### ISSUE THREAD

**Issue by vGhost2000** [spiral/database#30]
# Feature request: AbstractTable::getComparator type hint

Поменять тип возвращаемого результата метода Spiral\Database\Schema\AbstractTable::getComparator с Spiral\Database\Schema\Comparator на ComparatorInterface, данное изменение позволит в кастомных драйверах, использующих кастомные "Driver"Table использовать кастомные "Comparator" реализующие данный интерфейс

# Feature request: AbstractTable :: getComparator type hint

Change the return type of the Spiral\Database\Schema\AbstractTable::getComparator method from Spiral\Database\Schema\Comparator to ComparatorInterface, this change will allow custom drivers using custom "Driver"Table to use custom "Comparator" that implement this interface

**Comment by wolfy-j** [comment]
Will be part of the next release.
