### ISSUE TITLE
`where between` with reverted order escapes the value as it is a column name

### ISSUE THREAD

**Issue by vvval** [spiral/database#42]
Between query supports reverted order where args are not values but fields:
```php
$source->where(
    123,
    'BETWEEN',
    'created', 'updated'
);
```
The output is equals to:
```sql
SELECT * FROM table_name WHERE "123" BETWEEN 'created' AND 'updated'
```
expected:
```sql
SELECT * FROM table_name WHERE 123 BETWEEN 'created' AND 'updated'
```

**Comment by vvval** [comment]
Update: I have to pass int value here as a string, because `Quoter::quote()` method requires a string as an input. Can the quoter be modified to ignore bool/numbers/null values while quoting expressions?

**Comment by wolfy-j** [comment]
Use new Parameter() instead of scalar value for the first argument and Expression for values.

**Comment by vvval** [comment]
Thanks
