### ISSUE TITLE
Проблема с транзакциями

### ISSUE THREAD

**Issue by porozhnyy** [spiral/database#50]
Через некоторое время работы воркера при попытке записать что-то в БД с использованием транзакции начинает появляться ошибка:
```php
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT SVP-3 does not exist in /app/vendor/spiral/database/src/Driver/Driver.php:471
Stack trace:
#0 /app/vendor/spiral/database/src/Driver/Driver.php(471): PDOStatement->execute()
#1 /app/vendor/spiral/database/src/Driver/Driver.php(323): Spiral\Database\Driver\Driver->statement('RELEASE SAVEPOI...', Array)
#2 /app/vendor/spiral/database/src/Driver/Driver.php(634): Spiral\Database\Driver\Driver->execute('RELEASE SAVEPOI...')
#3 /app/vendor/spiral/database/src/Driver/Driver.php(412): Spiral\Database\Driver\Driver->releaseSavepoint(-3)
#4 /app/vendor/cycle/orm/src/Transaction/Runner.php(70): Spiral\Database\Driver\Driver->commitTransaction()
#5 /app/vendor/cycle/orm/src/Transaction.php(137): Cycle\ORM\Transaction\Runner->complete()
#6 /app/app/src/Repository/SecretAuthKeyRepository.php(42): Cycle\ORM\Transaction->run()
```
Ошибка зависит от воркера RR, т.е. проблема не на стороне БД. С каждым следующим запросом номер SVP уменьшается(--) на единицу. Предварительно проблема в дисконнекте воркера от MySQL и последующем реконнекте. Потенциально проблемное место:
vendor/spiral/database/src/Driver/Driver.php:353
```php
public function beginTransaction(string $isolationLevel = null): bool
{
    $this->transactionLevel++;
    if ($this->transactionLevel === 1) {
        if ($isolationLevel !== null) {
            $this->setIsolationLevel($isolationLevel);
        }
        if ($this->logger !== null) {
            $this->logger->info('Begin transaction');
        }
        try {
            return $this->getPDO()->beginTransaction();
        } catch (Throwable  $e) {
            $e = $this->mapException($e, 'BEGIN TRANSACTION');
            if (
                $e instanceof StatementException\ConnectionException
                && $this->options['reconnect']
            ) {
                $this->disconnect();
                try {
                    return $this->getPDO()->beginTransaction();
                } catch (Throwable $e) {
                    throw $this->mapException($e, 'BEGIN TRANSACTION');
                }
            }
        }
    }
    $this->createSavepoint($this->transactionLevel);
    return true;
}
```
вызов `$this->disconnect();` где вунтри
vendor/spiral/database/src/Driver/Driver.php:271
```php
public function disconnect(): void
{
    try {
        $this->queryCache = [];
        $this->pdo = null;
    } catch (Throwable $e) {
        // disconnect error
        if ($this->logger !== null) {
            $this->logger->error($e->getMessage());
        }
    }
    $this->transactionLevel = 0;
}
```
`$this->transactionLevel = 0;` - присваивается 0

**Comment by wolfy-j** [comment]
Предположительно поправили в последнем релизе.

**Comment by AdeAttwood** [comment]
I'm getting the same exception on `SPV0` not sure if it's related. It's coming from [spiral/migrations](https://github.com/spiral/migrations/blob/master/src/Migrator.php#L157) when running migrations.

```php
while (($migration = $migrator->run()) !== null) {
    $output->writeln("+ {$migration->getState()->getName()}");
}
```
```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT SVP0 does not exist
```

I think this is running execute on a `CREATE TABLE` statement that implicitly commits the transaction. Then when you try to commit the transaction it throws an exception that is caught and then the `rollBack` is called and dose not have a save point to go back to. The below snippet is from https://github.com/spiral/database/blob/master/src/Database.php#L244-L254 and if you wrap the `commit` in a try you get "There is no active transaction"

```diff
try {
    $result = $callback($this);
-   $this->commit();
+   try {
+       $this->commit();
+   } catch (Throwable $e) {
+       $e->getMessage(); // "There is no active transaction"
+   }

    return $result;
} catch (Throwable $e) {
    $this->rollBack();
    throw $e;
}
```

I have managed to fix the issue by wrapping the `$this->getPDO()->commit()` in `$this->getPDO()->inTransaction()` only commit if there is an active transaction in the [driver](https://github.com/spiral/database/blob/master/src/Driver/Driver.php#L409). 

```diff
try {
-    return $this->getPDO()->commit();
+    if ($this->getPDO()->inTransaction()) {
+        return $this->getPDO()->commit();
+    }
} catch (Throwable $e) {
    throw $this->mapException($e, 'COMMIT TRANSACTION');
}
```

It is also worth mentioning I am only getting this on php 8 it is working OK on 7.4. Don't know what the next steps are, I am happy to make a PR if your happy with the `$this->getPDO()->inTransaction()` fix.

**Comment by roxblnfk** [comment]
Об ошибке `PDOException: There is no active transaction`:

Прошёл по всему стеку и выяснил, что транзакцию прерывает, например, `CREATE TABLE` в [`$pdo->execute()`](https://github.com/spiral/database/blob/a729662ae424cc18b9b57bdbaf6742caeec98a8e/src/Driver/Driver.php#L474).

Полагаю, что это связано с тем, что [`$pdo->beginTransaction()`](https://github.com/spiral/database/blob/a729662ae424cc18b9b57bdbaf6742caeec98a8e/src/Driver/Driver.php#L367) не срабатывает должным образом.

Похоже на то, что транзакция начинается (вызов `$pdo->inTransaction()` после `beginTransaction()` возвращает `true`), но при этом не выключается режим автоматической фиксации транзакции, как написано в документации.

Воспроизводится на php 8 + mysql (5.7, 8.0)

**Comment by roxblnfk** [comment]
Возможно пофикшено в https://github.com/spiral/database/pull/66

**Comment by AdeAttwood** [comment]
> Possibly fixed in # 66

I think so. I haven't had this issue in a while. This was also suggested in https://github.com/spiral/database/pull/62#issuecomment-804054923

**Comment by roxblnfk** [comment]
Also covered by tests in https://github.com/cycle/database/pull/16
