### ISSUE TITLE
Statement->fetchAll(\PDO::FETCH_OBJ) returns arrays

### ISSUE THREAD

**Issue by guilhermeaiolfi** [spiral/database#53]
Hi,

the following query should returns an array of anonymous objects 
```php
$items = $database->table("any_table")->limit(3)->fetchAll(\PDO::FETCH_OBJ);
``` 

Instead, it is returning an array of arrays. Using the ```fetchAll``` directly as:

```php
$q = $pdo->query("select * from any_table limit 3");
$items = $q->fetchAll(\PDO::FETCH_OBJ);
```

 works as expected.

Apache/2.4.46 (Win64) OpenSSL/1.1.1g PHP/7.4.10

**Comment by guilhermeaiolfi** [comment]
OK, I've found the problem, in ```SelectQuery:fetchAll``` we have no args:

```php
   public function fetchAll(): array
    {
        $st = $this->run();
        try {
            return $st->fetchAll();
        } finally {
            $st->close();
        }
    }
```

So it always gets the default which is FETCH_ASSOC.

```php
   public function fetchAll(int $mode = Statement::FETCH_ASSOC ): array
    {
        $st = $this->run();
        try {
            return $st->fetchAll($mode);
        } finally {
            $st->close();
        }
    }
```

should do the tricky. If that's ok I can create a pull request for that.

**Comment by wolfy-j** [comment]
We'll appreciate PR for that.
