### ISSUE TITLE
В SELECT запросе в качестве колонки некорректно работает Expression

### ISSUE THREAD

**Issue by codercms** [spiral/database#55]
Компилятор запросов: PostgreSQL
Пример воспроизведения:
```php

use Spiral\Database\Injection\Expression;
//...
$select = $this->select()->buildQuery();

$rankQ = sprintf(
    'CASE WHEN %s ILIKE ? THEN 1 WHEN %s ILIKE ? THEN 2 WHEN %s ILIKE ? THEN 3 END AS rank',
    $params->field, // name
    $params->field, // name
    $params->field, // name
);

$select->columns(
    new Expression(
        $rankQ,
        "{$params->q}%", // any string
        "% {$params->q}%", // any string
        "%{$params->q}%" // any string
    )
);
```

Компилируется в:
```sql
SELECT "CASE WHEN name ILIKE ? THEN 1 WHEN name ILIKE ? THEN 2 WHEN name ILIKE ? THEN 3 END" AS "rank"
FROM "companies" AS "company"
```

А должно компилироваться в:
```sql
SELECT CASE WHEN name ILIKE ? THEN 1 WHEN name ILIKE ? THEN 2 WHEN name ILIKE ? THEN 3 END AS "rank"
FROM "companies" AS "company"
```

**Comment by wolfy-j** [comment]
Will be reviewed next week.

**Comment by wolfy-j** [comment]
We do not pass additional parameters via expression in columns. We will have to implement it. Hopefully sometime this week.

**Comment by wolfy-j** [comment]
Please use Fragment + custom db->query() method to query such complex relation for now.

**Comment by wolfy-j** [comment]
However, even after the update Expression won't be able to understand the difference between columns and SQL tokens, so you'll have to escape column names manually (at least for now, we will think how to improve it).

**Comment by codercms** [comment]
@wolfy-j hi! Could you provide an example how to bind custom parameters through Fragment + query semantic?

**Comment by codercms** [comment]
@wolfy-j I guess the problem is how the Compiler handles query expressions: https://github.com/spiral/database/blob/master/src/Driver/Compiler.php#L104 - it tries to quote the expression, but expression is a raw SQL statement and shouldn't be quoted.

**Comment by wolfy-j** [comment]
You can't bind parameters though Fragment yet, it will be part of the update.

**Comment by codercms** [comment]
@wolfy-j is there any progress with this issue?

**Comment by wolfy-j** [comment]
Not yet, dealing with other priorities.

**Comment by wolfy-j** [comment]
Please use Fragment (manual columns escaping is needed for now) instead of Expression. Parameters should be passed started with 2.7.19
