### ISSUE TITLE
Feature request: Create connection from DSN

### ISSUE THREAD

**Issue by shyim** [spiral/database#58]
Almost any cloud provider uses this day env variables like `DATABASE_URL`. It would be cool, when we just pass that url and get a connection

**Comment by SerafimArts** [comment]
@shyim why not use `getenv('DATABASE_URL')` in the db configuration?

**Comment by shyim** [comment]
Yea after that I have to do `parse_url` and assemble the config array. It would be fancy to have that out of the box :)

**Comment by SerafimArts** [comment]
Clear. Good idea.

**Comment by SerafimArts** [comment]
@shyim sry for the delay. Can you please provide an example of your DSN string?

**Comment by shyim** [comment]
mysql:
`mysql://root:root@mysql:3306/sw6`

pgsql:
`postgres://main:main@127.0.0.1:32781/main`

**Comment by SerafimArts** [comment]
@shyim thanks

**Comment by roxblnfk** [comment]
Feature will be available in the `2.9.0` version.
