### ISSUE TITLE
Cannot create compound unique index in Postgres

### ISSUE THREAD

**Issue by codercms** [spiral/database#59]
This code creates **non** unique index:
```php
    $table = $this->database()->table('addresses')->getSchema();
    $table->column('id')->uuid();
    $table->setPrimaryKeys(['id']);

    $table->column('company_id')->uuid()->nullable(false);
    $table->column('country_id')->uuid()->nullable(false);

    $table->column('title')->text()->nullable(false);
    $table->column('note')->text();

    $table->timestamp('created_at')->nullable(false);
    $table->timestamp('updated_at')->nullable(false);
    $table->timestamp('deleted_at');

    $table->index(['company_id']);
    $table->index(['country_id']);
    $table->index(['company_id', 'title'])->unique(true); // <<<<<<<

    $table
        ->foreignKey(['company_id'])
        ->references('companies', ['id'], false)
        ->onUpdate('CASCADE')
        ->onDelete('RESTRICT');

    $table->save();
```

UPD:

This code also doesn't create unique index:

```php
$table->index(['title'])->unique(true);
$table->save();
```

**Comment by codercms** [comment]
Btw I have a question how to create column with **fixed** (not variable) length? Eg char[12]

**Comment by codercms** [comment]
@wolfy-j it seems like the [documentation](https://spiral.dev/docs/database-declaration) is outdated.
Just a few examples:
## Indexes
If you wish to add unique index you can change your code a little bit:
```
$schema->column('email')->index(); //You can also use alternative declaration for simple indexes <<<< not working: Undefined abstract/virtual type 'index'

$schema->column('email')->unique(); //Simple unique index << not working Undefined abstract/virtual type 'unique'
$schema->index(['name', 'email'])->unique(true);  //Compound unique index <<< not working
```

My version of `spiral/database` package is v2.7.19

**Comment by wolfy-j** [comment]
Sounds like we def have outdated docs, you can no longer create index on column() object. You must call index() explicitly. 

You can create column with fixed size using `string(size)` method. I'm not sure if PG allows you to create indexes on `TEXT` fields, so that might be the case.

Can you check that, and if it still happens we will check the tests. It should be working since we use it at live projects.

**Comment by codercms** [comment]
@wolfy-j PG is ok with text indexes, btw PG in underhood stores VARCHAR in the same way as a TEXT.

```php
$schema->index(['name', 'email'])->unique(true);  //Compound unique index <<< not working
```

As I wrote above this code does not create unique index, it's just create compound **not** unique index.

**Comment by wolfy-j** [comment]
I just opened the test:

```php
// ...
$schema->column('name')->text();
$schema->column('email')->text();
$schema->index(['name', 'email'])->unique(true);

$schema->save();
```

And the result:

```sql
CREATE TABLE "table" (
    "id" serial NOT NULL,
    "name" text NULL,
    "email" text NULL,
    PRIMARY KEY ("id")
)
CREATE UNIQUE INDEX "table_index_name_email_5fbb773f8e4d6" ON "table" ("name", "email")
```

The introspection worked out properly as well.

Can you share with me the SQL code generated?

**Comment by codercms** [comment]
@wolfy-j whoops, that was a problem with displaying unique index in the PgAdmin app :) Sorry
