### ISSUE TITLE
Максимальная длина varchar

### ISSUE THREAD

**Issue by vagrus** [spiral/database#70]
https://github.com/spiral/database/blob/626b7fc2a550423fa0a354ec76400bafe2eae3fe/src/Schema/AbstractColumn.php#L616

И Postgre и Mysql давно уже поддерживают varchar размером >60Kb, что даже в 8-байтных кодировках больше 8000 символов. Не пора ли и здесь снять ограничение?

**Comment by roxblnfk** [comment]
@vagrus Pull Request приветствуется :)
